services:
  keycloak:
      image: quay.io/keycloak/keycloak:latest
      container_name: keycloak
      command: >
          start --http-enabled=true --proxy-headers=xforwarded
      environment:
        - KC_DB=postgres
        - KC_DB_URL=jdbc:postgresql://keycloak-postgres:5432/
        - KC_DB_USERNAME=${POSTGRES_USER}
        - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
        - KC_HOSTNAME=${KC_HOSTNAME}
        - KC_BOOTSTRAP_ADMIN_USERNAME=${KC_BOOTSTRAP_ADMIN_USERNAME}
        - KC_BOOTSTRAP_ADMIN_PASSWORD=${KC_BOOTSTRAP_ADMIN_PASSWORD}
        - KC_SPI_TRUSTSTORE_FILE_ENABLED=true
        - KC_SPI_TRUSTSTORE_FILE_FILE=/opt/keycloak/conf/cacerts
        - KC_SPI_TRUSTSTORE_FILE_PASSWORD=changeit
        - KC_SPI_TRUSTSTORE_FILE_HOSTNAME_VERIFICATION_POLICY=ANY
        # Custom settings for reverse proxy with non-standard port
        - KC_PROXY=edge             # This tells Keycloak it's behind a proxy
        - KC_HOSTNAME_STRICT=false  # Disable strict hostname checking for debug
        - KC_HOSTNAME_PORT=58443    # This forces Keycloak to use the correct port in its generated links
      ports:
        - "${KEYCLOAK_HTTP_PORT}:8080"
      volumes:
        - /opt/keycloak/runtime/keycloak_conf:/opt/keycloak/conf
        - /opt/keycloak/providers:/opt/keycloak/providers
      depends_on:
        - keycloak-postgres

  keycloak-postgres:
      image: postgres:15
      container_name: keycloak-postgres
      environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      ports:
        - "5432:5432"
      volumes:
        - /opt/keycloak/runtime/postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/keycloak/runtime/postgres_data
